package Ficheros;

// Enumeramos los distintos géneros de libros
public enum Genero {
    drama,
    acción,
    terror,
    comedia,
    suspense,
    bélica,
    aventura,
    documental,
    deportes,
    ciencia_ficción,
    animación,
    super_heroes,
    musical,
    familiar,
    infantil,
    magia,
    historia,
    política,
    filosofía,
    educación,
    psicología,
    economía,
    ciencia,
    matemáticas,
    bellas_artes,
    pintura,
    biografía,
    humor,
    autoayuda,
    éxito_personal,
    ley_de_atracción,
    liderazgo,
    espiritualidad,
    fantasía,
    divulgación_científica,
    anatomía,
    astronomía,
    epopeya,
    misterio,
    exito_personal,
    biología,
    ficción
}
